[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
JSON_AS_ASCII = false


EXTENSIONS = [
    "codesevenapi.ext.api:init_app", 
    "codesevenapi.ext.auth:init_app", 
    "codesevenapi.ext.cli:init_app", 
    "codesevenapi.ext.db:init_app"
]


[development]
DEBUG_MODE = true
SQLALCHEMY_DATABASE_URI = "sqlite:///codesevenapi.db"


[production]
DEBUG_MODE = false
SQLALCHEMY_DATABASE_URI = "sqlite:///codesevenapi.db"


[test]
DEBUG_MODE = false
SQLALCHEMY_DATABASE_URI = "sqlite:///codesevenapi.db"
